spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/Desktop/jwt-h2/jwt;AUTO_SERVER=TRUE
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
        orm:
          jdbc:
            bind: trace
          springframework: # ??!
            security: debug # ??!

auth:
  jwt:
    issuer: team.sparta.com
    secret: HimyNamEIsBaNGJunhEEIm25TeaRsOlD
    accessTokenExpirationHour: 168


